apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akhq.fullname" . }}
  namespace: {{ include "akhq.namespace" . }}
  labels:
    {{- include "akhq.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "akhq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "akhq.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: akhq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: MICRONAUT_CONFIG_FILES
              value: /app/application.yml
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/application.yml
              subPath: application.yml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "akhq.fullname" . }}-config
