{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{ include "postgres.namespace" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.auth.database | quote }}
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ required "auth.password is required when auth.createSecret is true" .Values.auth.password | quote }}
{{- end }}
