apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  namespace: {{ include "redis.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port {{ .Values.service.port }}
    dir /data
    appendonly {{ ternary "yes" "no" .Values.redis.appendOnly }}
    appendfsync {{ .Values.redis.appendFsync }}
    maxmemory {{ .Values.redis.maxmemory }}
    maxmemory-policy {{ .Values.redis.maxmemoryPolicy }}
