apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluent-bit.fullname" . }}
  namespace: {{ include "fluent-bit.namespace" . }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
automountServiceAccountToken: true
