namespaceOverride: ""

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

service:
  port: 5432

auth:
  createSecret: false
  existingSecret: postgres
  database: postgres
  username: postgres
  password: ""

storage:
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

databases:
  - customer_service
  - account_service
  - transaction_service
  - payment_service
  - notification_service
