namespaceOverride: digital-bank-sit

image:
  repository: redis
  tag: "7.4-alpine"

redis:
  appendOnly: true
  appendFsync: everysec
  maxmemory: "256mb"
  maxmemoryPolicy: noeviction

auth:
  existingSecret: redis
  secretKey: REDIS_PASSWORD

networkPolicy:
  enabled: true
  allowedNamespace: digital-bank-sit

storage:
  size: 1Gi
