namespaceOverride: ""

fixtures:
  enabled: false

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

postgres:
  host: postgres
  port: 5432
  existingSecret: postgres

job:
  backoffLimit: 6
  activeDeadlineSeconds: 300
